// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // android/ and ios/ are generated by `expo prebuild` and gitignored;
    // drizzle/ is generated by drizzle-kit. Linting any of them reports on
    // code nobody edits by hand and that regeneration would overwrite.
    ignores: ["dist/*", "android/*", "ios/*", "drizzle/*", ".expo/*"],
  },
  {
    rules: {
      // A web rule: unescaped entities can break HTML markup. React Native
      // <Text> children are plain strings, so there's nothing to break, and
      // this codebase writes straight apostrophes throughout — honouring it
      // would leave nine screens curly and every other string not.
      "react/no-unescaped-entities": "off",
    },
  },
]);
