// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // android/ and ios/ are generated by `expo prebuild` and gitignored;
    // drizzle/ is generated by drizzle-kit. Linting any of them reports on
    // code nobody edits by hand and that regeneration would overwrite.
    ignores: ["dist/*", "android/*", "ios/*", "drizzle/*", ".expo/*"],
  },
]);
