const { withAppBuildGradle, withGradleProperties } = require("@expo/config-plugins");

// Turns R8's *optimization* pass on for release builds (Play Console
// advisory on 3.1.0, "Improve your app's memory and performance with R8
// optimisation").
//
// Minification and resource shrinking were already enabled via
// expo-build-properties, but the React Native template's app/build.gradle
// points at getDefaultProguardFile("proguard-android.txt") -- the
// *non-optimizing* default, which contains `-dontoptimize`. So R8 was
// shrinking and obfuscating while skipping the optimization phase
// entirely. Android's own docs say support for that file "has been
// dropped, because it includes -dontoptimize" and to use
// proguard-android-optimize.txt instead.
//
// The second half is optimized resource shrinking, which AGP 8.12 (pinned
// by react-native 0.86) needs told explicitly; AGP 9 applies it on its own
// once shrinkResources is on. We don't force AGP 9 -- it comes from
// RN/Expo and overriding it on SDK 57 is unsupported, so that part of the
// advisory waits for an SDK bump.
//
// android/ is gitignored and regenerated by `expo prebuild`, which is why
// both edits live here rather than in the generated files -- same reason
// withAppShortcuts.js exists.

const DEFAULT_PROGUARD = 'getDefaultProguardFile("proguard-android.txt")';
const OPTIMIZED_PROGUARD = 'getDefaultProguardFile("proguard-android-optimize.txt")';
const RESOURCE_SHRINKING_KEY = "android.r8.optimizedResourceShrinking";

function withOptimizedProguardFile(config) {
  return withAppBuildGradle(config, (cfg) => {
    const contents = cfg.modResults.contents;
    // Idempotent: prebuild may run against an already-patched tree.
    if (contents.includes(OPTIMIZED_PROGUARD)) return cfg;
    if (!contents.includes(DEFAULT_PROGUARD)) {
      throw new Error(
        `withR8Optimization: expected ${DEFAULT_PROGUARD} in app/build.gradle. ` +
          "The React Native template changed -- check which default ProGuard file it now uses.",
      );
    }
    cfg.modResults.contents = contents.replace(DEFAULT_PROGUARD, OPTIMIZED_PROGUARD);
    return cfg;
  });
}

function withOptimizedResourceShrinking(config) {
  return withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === "property" && item.key === RESOURCE_SHRINKING_KEY,
    );
    if (existing) {
      existing.value = "true";
      return cfg;
    }
    cfg.modResults.push({ type: "property", key: RESOURCE_SHRINKING_KEY, value: "true" });
    return cfg;
  });
}

module.exports = function withR8Optimization(config) {
  return withOptimizedResourceShrinking(withOptimizedProguardFile(config));
};
