const { withAndroidManifest, withStringsXml, withDangerousMod, AndroidConfig } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// Adds Android static app-icon-longpress shortcuts (Expense / Income /
// Transfer) alongside the three new home-screen widgets. android/ is
// regenerated by `expo prebuild`, so this has to go through a config
// plugin rather than hand-editing the generated
// AndroidManifest.xml/res/xml -- same reason modules/widget-bridge exists
// as a local Expo module instead of hand-edited native files.
//
// Reuses the exact spendingtracker://transaction/new?type=... deep link
// the home screen widgets already use (see
// modules/widget-bridge/android/.../WidgetSharedUtil.kt) -- no new
// navigation/route handling needed, app/transaction/new.tsx already reads
// this param.

const SHORTCUTS = [
  { id: "add_expense", type: "expense", shortLabel: "Expense", longLabel: "Add expense" },
  { id: "add_income", type: "income", shortLabel: "Income", longLabel: "Add income" },
  { id: "add_transfer", type: "transfer", shortLabel: "Transfer", longLabel: "Add transfer" },
];

function shortcutsXml(applicationId) {
  const mainActivityClass = `${applicationId}.MainActivity`;
  const shortcutElements = SHORTCUTS.map(
    (s) => `  <shortcut
      android:shortcutId="${s.id}"
      android:enabled="true"
      android:icon="@mipmap/ic_launcher"
      android:shortcutShortLabel="@string/shortcut_${s.type}_short"
      android:shortcutLongLabel="@string/shortcut_${s.type}_long">
    <intent
        android:action="android.intent.action.VIEW"
        android:targetPackage="${applicationId}"
        android:targetClass="${mainActivityClass}"
        android:data="spendingtracker://transaction/new?type=${s.type}" />
  </shortcut>`,
  ).join("\n");
  return `<?xml version="1.0" encoding="utf-8"?>\n<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">\n${shortcutElements}\n</shortcuts>\n`;
}

function withAppShortcutsManifest(config) {
  return withAndroidManifest(config, (config) => {
    const mainActivity = AndroidConfig.Manifest.getMainActivityOrThrow(config.modResults);
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      mainActivity,
      "android.app.shortcuts",
      "@xml/shortcuts",
      "resource",
    );
    return config;
  });
}

function withAppShortcutsStrings(config) {
  return withStringsXml(config, (config) => {
    const strings = config.modResults.resources.string ?? [];
    for (const s of SHORTCUTS) {
      const shortName = `shortcut_${s.type}_short`;
      const longName = `shortcut_${s.type}_long`;
      if (!strings.some((item) => item.$.name === shortName)) {
        strings.push(AndroidConfig.Resources.buildResourceItem({ name: shortName, value: s.shortLabel }));
      }
      if (!strings.some((item) => item.$.name === longName)) {
        strings.push(AndroidConfig.Resources.buildResourceItem({ name: longName, value: s.longLabel }));
      }
    }
    config.modResults.resources.string = strings;
    return config;
  });
}

function withAppShortcutsXmlResource(config) {
  return withDangerousMod(config, [
    "android",
    async (config) => {
      const applicationId = config.android?.package;
      if (!applicationId) {
        throw new Error("withAppShortcuts requires app.json's android.package to be set");
      }
      const xmlDir = path.join(config.modRequest.platformProjectRoot, "app", "src", "main", "res", "xml");
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, "shortcuts.xml"), shortcutsXml(applicationId));
      return config;
    },
  ]);
}

module.exports = function withAppShortcuts(config) {
  config = withAppShortcutsStrings(config);
  config = withAppShortcutsManifest(config);
  config = withAppShortcutsXmlResource(config);
  return config;
};
