import {
  Activity,
  ArrowLeftRight,
  Backpack,
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Cake,
  Calculator,
  CalendarDays,
  CalendarSync,
  Car,
  ChevronLeft,
  ChevronRight,
  CircleParking,
  CircleUserRound,
  Clapperboard,
  Coffee,
  Coins,
  Copy,
  CreditCard,
  Droplets,
  Dumbbell,
  Flag,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HeartPulse,
  Headphones,
  Home,
  Hotel,
  Key,
  Landmark,
  LayoutDashboard,
  Leaf,
  LineChart,
  Lightbulb,
  type LucideIcon,
  Luggage,
  MapPin,
  Mountain,
  MoreHorizontal,
  Music,
  Package,
  Pencil,
  Percent,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plus,
  Receipt,
  Recycle,
  Scissors,
  Settings,
  Shapes,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TrainFront,
  Trophy,
  Users,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  X,
  Zap,
  PawPrint,
  Info,
} from "lucide-react-native";

// Every category/account `icon` column stores a plain, untyped string —
// historically a MaterialCommunityIcons name (spec.md's icon system predates
// this design refresh). Swapping the icon library is a rendering-layer
// change only: this map translates each already-persisted slug to its
// Lucide equivalent so existing data keeps resolving correctly. Everything
// past the first block is a new key introduced by constants/iconLibrary.ts's
// expanded picker.
export const ICON_MAP: Record<string, LucideIcon> = {
  // structural/UI icons
  "view-dashboard-outline": LayoutDashboard,
  "wallet-outline": Wallet,
  "swap-horizontal": ArrowLeftRight,
  "calendar-sync-outline": CalendarSync,
  "shape-outline": Shapes,
  "account-circle-outline": CircleUserRound,
  "pencil-outline": Pencil,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "calendar-month-outline": CalendarDays,
  "content-copy": Copy,
  "trash-can-outline": Trash2,
  // V2 global-shell icons (spec.md §5.19)
  "settings-outline": Settings,
  "information-outline": Info,
  "tag-outline": Tag,
  "chart-line": LineChart,
  plus: Plus,
  close: X,
  logo: Mountain,
  // legacy category/account icon picker options (constants/categoryIcons.ts,
  // constants/accountTypes.ts) — kept so already-persisted data renders
  shopping: ShoppingBag,
  cart: ShoppingCart,
  "silverware-fork-knife": UtensilsCrossed,
  home: Home,
  briefcase: Briefcase,
  "heart-pulse": HeartPulse,
  gift: Gift,
  movie: Clapperboard,
  "book-open": BookOpen,
  car: Car,
  airplane: Plane,
  "credit-card": CreditCard,
  cash: Banknote,
  "trending-up": TrendingUp,
  cellphone: Smartphone,
  wifi: Wifi,
  flash: Zap,
  "emoticon-happy": Smile,
  "dots-horizontal": MoreHorizontal,
  receipt: Receipt,
  "piggy-bank": PiggyBank,
  bank: Landmark,
  // expanded icon library (constants/iconLibrary.ts) — new keys, full
  // freedom of choice for categories and accounts
  coffee: Coffee,
  pizza: Pizza,
  wine: Wine,
  cake: Cake,
  shirt: Shirt,
  key: Key,
  hammer: Hammer,
  sofa: Sofa,
  lightbulb: Lightbulb,
  droplets: Droplets,
  fuel: Fuel,
  bus: Bus,
  train: TrainFront,
  bike: Bike,
  parking: CircleParking,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  activity: Activity,
  gamepad: Gamepad2,
  music: Music,
  headphones: Headphones,
  sparkles: Sparkles,
  hotel: Hotel,
  "map-pin": MapPin,
  luggage: Luggage,
  "trending-down": TrendingDown,
  percent: Percent,
  calculator: Calculator,
  shield: Shield,
  coins: Coins,
  users: Users,
  baby: Baby,
  "paw-print": PawPrint,
  scissors: Scissors,
  "graduation-cap": GraduationCap,
  backpack: Backpack,
  star: Star,
  flag: Flag,
  target: Target,
  trophy: Trophy,
  package: Package,
  leaf: Leaf,
  recycle: Recycle,
};

export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? MoreHorizontal;
}
