import { backupFilename, parseBackupEntry } from "../services/dropboxBackupNaming";

describe("backupFilename", () => {
  it("names an auto backup by date only", () => {
    expect(backupFilename("auto", new Date(2026, 7, 28, 14, 30, 45))).toBe("backup-auto-2026-08-28.db");
  });

  it("names a manual backup with a time suffix, so same-day manual backups don't collide", () => {
    expect(backupFilename("manual", new Date(2026, 7, 28, 14, 30, 45))).toBe(
      "backup-manual-2026-08-28T143045.db",
    );
  });

  it("pads single-digit hours/minutes/seconds", () => {
    expect(backupFilename("manual", new Date(2026, 0, 5, 4, 5, 6))).toBe("backup-manual-2026-01-05T040506.db");
  });
});

describe("parseBackupEntry", () => {
  it("parses an auto backup filename", () => {
    const entry = parseBackupEntry("backup-auto-2026-08-28.db");
    expect(entry?.kind).toBe("auto");
    expect(entry?.path).toBe("/backup-auto-2026-08-28.db");
    expect(entry?.label).toContain("Automatic");
  });

  it("parses a manual backup filename", () => {
    const entry = parseBackupEntry("backup-manual-2026-08-28T143045.db");
    expect(entry?.kind).toBe("manual");
    expect(entry?.label).toContain("Manual");
  });

  it("round-trips: parsing a name generated by backupFilename yields the same kind", () => {
    const now = new Date(2026, 7, 28, 9, 15, 0);
    const autoEntry = parseBackupEntry(backupFilename("auto", now));
    const manualEntry = parseBackupEntry(backupFilename("manual", now));
    expect(autoEntry?.kind).toBe("auto");
    expect(manualEntry?.kind).toBe("manual");
  });

  it("sorts newer entries first when combined and sorted by timestampMs", () => {
    const older = parseBackupEntry("backup-auto-2026-08-20.db")!;
    const newer = parseBackupEntry("backup-manual-2026-08-28T090000.db")!;
    const sorted = [older, newer].sort((a, b) => b.timestampMs - a.timestampMs);
    expect(sorted[0]).toBe(newer);
  });

  it("returns null for a name that doesn't match either pattern", () => {
    expect(parseBackupEntry("random-file.txt")).toBeNull();
    expect(parseBackupEntry("backup-auto-2026-08-28.txt")).toBeNull();
  });
});
